% Radar Tracking Tasks
radarTrackTask1 = TaskSpace.RadarTrackingTask( ...
    NamedConst.RADAR_TRACK_CYCLE_TIME,NamedConst.MEDIUM_PRIORITY,...
    randi([1 NamedConst.RADAR_TRACK_CYCLE_TIME]));

radarTrackTask2 = TaskSpace.RadarTrackingTask( ...
    NamedConst.RADAR_TRACK_CYCLE_TIME,NamedConst.MEDIUM_PRIORITY,...
    randi([1 NamedConst.RADAR_TRACK_CYCLE_TIME]));

radarTrackTask3 = TaskSpace.RadarTrackingTask( ...
    NamedConst.RADAR_TRACK_CYCLE_TIME,NamedConst.MEDIUM_PRIORITY,...
    randi([1 NamedConst.RADAR_TRACK_CYCLE_TIME]));

radarTrackTask4 = TaskSpace.RadarTrackingTask( ...
    NamedConst.RADAR_TRACK_CYCLE_TIME,NamedConst.MEDIUM_PRIORITY,...
    randi([1 NamedConst.RADAR_TRACK_CYCLE_TIME]));

radarTrackTask5 = TaskSpace.RadarTrackingTask( ...
    NamedConst.RADAR_TRACK_CYCLE_TIME,NamedConst.MEDIUM_PRIORITY,...
    randi([1 NamedConst.RADAR_TRACK_CYCLE_TIME]));

radarTrackTask6 = TaskSpace.RadarTrackingTask( ...
    NamedConst.RADAR_TRACK_CYCLE_TIME,NamedConst.MEDIUM_PRIORITY,...
    randi([1 NamedConst.RADAR_TRACK_CYCLE_TIME]));
