function [ range_m ] = RadarRangeEqn( ...
    transmitPowerDb, transmitAntennaGain, ...
    receiveAntennaGain, wavelength_m_power_2_db, ...
    targetCrossSection_db, ...
    sensitivity, L2_db)

% Calculates the effective detection Range

%% Constants Defintion
FourPiCube_db = DbConvert((4 * pi)^3);  % (4 * pi)^3 in db

%% Actual Calculation
range_m_power_4_db = transmitPowerDb + ...
    transmitAntennaGain + ...
    receiveAntennaGain + wavelength_m_power_2_db ...
    + targetCrossSection_db + L2_db ...
    - FourPiCube_db - sensitivity;

range_m_power_4 = DbUnConvert(range_m_power_4_db);
range_m = range_m_power_4 .^ 0.25;

end

